apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
  labels:
    app: reservation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reservation
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation
          image: jdwon.azurecr.io/reservation:latest
          ports:
            - containerPort: 8080
          livenessProbe:
            tcpSocket:
              port: 8081
            initialDelaySeconds: 5
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: reservation
  labels:
    app: reservation
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: reservation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deposit
  labels:
    app: deposit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deposit
  template:
    metadata:
      labels:
        app: deposit
    spec:
      containers:
        - name: deposit
          image: jdwon.azurecr.io/deposit:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: deposit
  labels:
    app: deposit
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: deposit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant
  labels:
    app: restaurant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant
  template:
    metadata:
      labels:
        app: restaurant
    spec:
      containers:
        - name: restaurant
          image: jdwon.azurecr.io/restaurant:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: restaurant
  labels:
    app: restaurant
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: restaurant
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customercenter 
  labels:
    app: customercenter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customercenter
  template:
    metadata:
      labels:
        app: customercenter
    spec:
      containers:
        - name: customercenter
          image: jdwon.azurecr.io/customercenter:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: customercenter
  labels:
    app: customercenter
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: customercenter
