server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://localhost:8081
          predicates:
            - Path=/reservations/** 
        - id: deposit
          uri: http://localhost:8082
          predicates:
            - Path=/deposits/** 
        - id: customercenter
          uri: http://localhost:8083
          predicates:
            - Path= /myPages/**
        - id: restaurant
          uri: http://localhost:8084
          predicates:
            - Path=/restaurants/** 
        - id: recommendation
          uri: http://localhost:8085
          predicates:
            - Path=/recommendations/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: reservation
          uri: http://reservation:8080
          predicates:
            - Path=/reservations/** 
        - id: deposit
          uri: http://deposit:8080
          predicates:
            - Path=/deposits/** 
        - id: customercenter
          uri: http://customercenter:8080
          predicates:
            - Path= /myPages/**
        - id: restaurant
          uri: http://restaurant:8080
          predicates:
            - Path=/restaurants/** 
        - id: recommendation
          uri: http://recommendation:8080
          predicates:
            - Path=/recommendations/** 
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 80
