apiVersion: apps/v1
kind: Deployment
metadata:
  name: deposit
  labels:
    app: deposit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: deposit
  template:
    metadata:
      labels:
        app: deposit
    spec:
      containers:
        - name: deposit
          image: username/deposit:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5